stages:
  data_splitting:
    cmd: python src/data/train_test_split.py
    deps:
    - data/raw_data
    - src/data/train_test_split.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  data_normalization:
    cmd: python src/data/normalization.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalization.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/grid_xgb.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/grid_xgb.py
    outs:
    - models/best_params.pkl
  model_training:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data/X_train.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/trained_xgb_model.joblib
  model_evaluation:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
    - models/trained_xgb_model.joblib
    - src/models/evaluate_model.py
    metrics:
    - metrics/scores.json:
        cache: false
